//
// Generated file, do not edit! Created by opp_msgtool 6.0 from AgentPacket.msg.
//

#ifndef __AGENTPACKET_M_H
#define __AGENTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AgentPacket;
// cplusplus {{
#include <omnetpp.h>
// }}

/**
 * Class generated from <tt>AgentPacket.msg:7</tt> by opp_msgtool.
 * <pre>
 * // Define o pacote customizado
 * packet AgentPacket
 * {
 *     string srcAgent;   // ID do agente de origem (ex: "agent_0")
 *     string destAgent;  // ID do agente de destino (ex: "agent_1")
 *     string payload;    // O JSON original da mensagem FIPA-ACL
 * }
 * </pre>
 */
class AgentPacket : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string srcAgent;
    omnetpp::opp_string destAgent;
    omnetpp::opp_string payload;

  private:
    void copy(const AgentPacket& other);

  protected:
    bool operator==(const AgentPacket&) = delete;

  public:
    AgentPacket(const char *name=nullptr, short kind=0);
    AgentPacket(const AgentPacket& other);
    virtual ~AgentPacket();
    AgentPacket& operator=(const AgentPacket& other);
    virtual AgentPacket *dup() const override {return new AgentPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSrcAgent() const;
    virtual void setSrcAgent(const char * srcAgent);

    virtual const char * getDestAgent() const;
    virtual void setDestAgent(const char * destAgent);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AgentPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AgentPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AgentPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<AgentPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __AGENTPACKET_M_H

