[General]
# Aponta para a rede que será gerada dinamicamente pelo seu script Python
network = DynamicNetwork

# Mantém o scheduler padrão para a co-simulação
scheduler-class = "omnetpp::cSequentialScheduler"

# Limite de tempo da simulação (pode ser ajustado conforme a necessidade do Mosaik)
sim-time-limit = 1000s

# =============================================================================
# NOTA: Os parâmetros de largura de banda, drop_probability e jitter_mean
# foram removidos deste arquivo!
# 
# Motivo: Agora, esses comportamentos são aplicados automaticamente pelas 
# conexões geradas no arquivo DynamicNetwork.ned com base nos perfis (Link_5G, 
# Link_4G, etc.) definidos na biblioteca Profiles.ned.
# =============================================================================

# =============================================================================
# CORINGA DE PARÂMETROS
# Preenche automaticamente qualquer "agent_id" com uma string vazia para 
# satisfazer o validador do OMNeT++, já que agora o C++ descobre seu nome sozinho.
# =============================================================================
**.agent_id = ""