[General]
network = CoSimulationNetwork
scheduler-class = "omnetpp::cSequentialScheduler"
sim-time-limit = 1000s

# Largura de banda
**.node_0.bandwidth_bps = 50000.0

# Drop de Pacotes: 15% de probabilidade de um pacote ser destruído (0.15)
**.node_0.drop_probability = 0.15

# Jitter: Injeta uma média de 50ms de atraso caótico nas filas
**.node_0.jitter_mean = 0.05