[General]
network = CoSimulationNetwork

# Importante: Como o mosaik controla o tempo, 
# o OMNeT++ não deve tentar correr o mais rápido possível (CPU 100%)
# se você quiser observar em tempo real, mas para co-simulação pura
# o modo abaixo é o padrão.
scheduler-class = "omnetpp::cSequentialScheduler"

# Se você quiser que o OMNeT++ termine caso o mosaik caia
sim-time-limit = 1000s