services:
  pade:
    build:
      context: .
      dockerfile: Dockerfile.pade
    container_name: pade
    networks:
      - sim_net
    ports:
      - "5678:5678"
    # Mapeia a pasta local 'pade_agents' para a pasta '/app/agents' no contentor
    volumes:
      - ./pade_agents:/app/agents
    stdin_open: true
    tty: true
    # O comando aponta exatamente para o caminho dentro da pasta mapeada
    command: python3 /app/agents/agent_example_1_mosaik_updated.py

  omnet_sim:
    build: ./omnet-dir
    container_name: omnet_sim
    networks:
      - sim_net
    expose:
      - "5555"
    volumes:
      - ./omnet-dir:/root/models 
    command: /bin/bash -c "source /root/omnetpp/setenv && opp_makemake -f --deep -O out -o sim_exec -lzmq && make && ./sim_exec -u Cmdenv -c General"

  mosaik_master:
    build: ./mosaik-dir
    container_name: mosaik_master
    networks:
      - sim_net
    depends_on:
      - omnet_sim
      - pade
    volumes:
      - ./mosaik-dir:/app
      
    command: sh -c "pip install pandas matplotlib && echo 'Aguardando o PADE arrancar...' && sleep 5 && python first.py && python plot_results.py"

networks:
  sim_net:
    driver: bridge